# Generated by Django 4.2.3 on 2023-07-15 13:59

import audiofield.fields
import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=250)),
                ('filename', models.CharField(max_length=255)),
                ('murl', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('singer', models.CharField(max_length=140)),
                ('info', models.TextField(max_length=140)),
                ('key', models.IntegerField(choices=[(0, 'Empty'), (1, 'C'), (2, 'C#'), (3, 'D'), (4, 'D#'), (5, 'E'), (6, 'F'), (7, 'F#'), (8, 'G'), (9, 'G#'), (10, 'A'), (11, 'A#'), (12, 'B')])),
                ('minor', models.BooleanField(default=False)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('language', models.IntegerField(choices=[(0, 'Empty'), (1, 'eng'), (2, 'kor'), (3, 'rus')])),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['timestamp'])),
                ('media', models.ManyToManyField(blank=True, related_name='song', to='songbook.mlinks')),
                ('publisher', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='song', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='song', to='songbook.tag')),
                ('translated', models.ManyToManyField(blank=True, related_name='translation', to='songbook.song')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='default.png', upload_to='profile_images/')),
                ('about_me', models.TextField(max_length=140)),
                ('mobile_no', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('body', models.CharField(max_length=140)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('language', models.CharField(max_length=5)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique_with=['created_on'])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Sunday service', max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('mlink', models.TextField(blank=True, null=True)),
                ('passage', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Final'), (2, 'Passed')], default=0)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['created'])),
                ('assigned', models.ManyToManyField(related_name='created', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('desired_key', models.IntegerField(choices=[(0, 'Empty'), (1, 'C'), (2, 'C#'), (3, 'D'), (4, 'D#'), (5, 'E'), (6, 'F'), (7, 'F#'), (8, 'G'), (9, 'G#'), (10, 'A'), (11, 'A#'), (12, 'B')])),
                ('listorder', models.IntegerField()),
                ('notes', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique_with=['created'])),
                ('assigned', models.ManyToManyField(related_name='assigned', to=settings.AUTH_USER_MODEL)),
                ('lists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='songbook.lists')),
                ('song', models.ManyToManyField(related_name='inlist', to='songbook.song')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('filename', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='songbook.song')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('filename', models.CharField(max_length=255)),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='audio/')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio', to='songbook.song')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
