# Generated by Django 4.2.3 on 2023-07-04 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default=2, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='listitem',
            name='desired_key',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'C'), (2, 'C#'), (3, 'D'), (4, 'D#'), (5, 'E'), (6, 'F'), (7, 'F#'), (8, 'G'), (9, 'G#'), (10, 'A'), (11, 'A#'), (12, 'B')]),
        ),
        migrations.AlterField(
            model_name='mlinks',
            name='mtype',
            field=models.IntegerField(choices=[(0, 'other'), (1, 'audio'), (2, 'youtube'), (3, 'image')]),
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'C'), (2, 'C#'), (3, 'D'), (4, 'D#'), (5, 'E'), (6, 'F'), (7, 'F#'), (8, 'G'), (9, 'G#'), (10, 'A'), (11, 'A#'), (12, 'B')]),
        ),
        migrations.AlterField(
            model_name='song',
            name='language',
            field=models.IntegerField(choices=[(0, 'Empty'), (1, 'eng'), (2, 'kor'), (3, 'rus')]),
        ),
    ]
