# Generated by Django 4.2.3 on 2023-07-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lists',
            name='days',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='next_year',
        ),
        migrations.RemoveField(
            model_name='lists',
            name='time',
        ),
    ]
