# Generated by Django 4.2.3 on 2023-07-17 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
