# Generated by Django 4.2.3 on 2023-07-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0002_remove_lists_days_remove_lists_next_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lists',
            name='mlink',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lists',
            name='passage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
