# Generated by Django 4.2.3 on 2023-07-17 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0002_alter_listitem_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listitem',
            name='lists',
        ),
        migrations.AddField(
            model_name='lists',
            name='items',
            field=models.ManyToManyField(related_name='lists', to='songbook.listitem'),
        ),
    ]
