# Generated by Django 4.2.3 on 2023-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0002_alter_post_options_post_created_on_post_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0),
        ),
    ]
