# Generated by Django 4.2.3 on 2023-07-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0003_song_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='minor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='media',
            field=models.ManyToManyField(blank=True, related_name='song', to='songbook.mlinks'),
        ),
    ]
