# Generated by Django 4.2.3 on 2023-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0003_remove_listitem_lists_lists_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='language',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
