# Generated by Django 4.2.3 on 2023-07-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songbook', '0004_alter_post_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('issue', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('contact_info', models.CharField(blank=True, max_length=140, null=True)),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Solved')], default=0)),
            ],
        ),
    ]
